FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-w -s" -o /bin/operator ./cmd/operator

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/operator /usr/local/bin/operator
CMD ["operator"]
