// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: afp/v1/policy_stream.proto

package afppolicystream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AFPPolicyStream_StreamPolicyUpdates_FullMethodName = "/afp.v1.policystream.AFPPolicyStream/StreamPolicyUpdates"
	AFPPolicyStream_PublishPolicyUpdate_FullMethodName = "/afp.v1.policystream.AFPPolicyStream/PublishPolicyUpdate"
)

// AFPPolicyStreamClient is the client API for AFPPolicyStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AFPPolicyStream is the Phase 2 runtime control plane.
// ConfigMap + fsnotify remains declarative law; this stream delivers sub-second injunctions.
type AFPPolicyStreamClient interface {
	// StreamPolicyUpdates pushes policy deltas and emergency overrides to sidecars.
	StreamPolicyUpdates(ctx context.Context, in *PolicySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyUpdate], error)
	// PublishPolicyUpdate injects a one-shot override (Kill Switch, emergency clamp).
	PublishPolicyUpdate(ctx context.Context, in *PolicyUpdate, opts ...grpc.CallOption) (*PolicyUpdateAck, error)
}

type aFPPolicyStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAFPPolicyStreamClient(cc grpc.ClientConnInterface) AFPPolicyStreamClient {
	return &aFPPolicyStreamClient{cc}
}

func (c *aFPPolicyStreamClient) StreamPolicyUpdates(ctx context.Context, in *PolicySubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PolicyUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AFPPolicyStream_ServiceDesc.Streams[0], AFPPolicyStream_StreamPolicyUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PolicySubscribeRequest, PolicyUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFPPolicyStream_StreamPolicyUpdatesClient = grpc.ServerStreamingClient[PolicyUpdate]

func (c *aFPPolicyStreamClient) PublishPolicyUpdate(ctx context.Context, in *PolicyUpdate, opts ...grpc.CallOption) (*PolicyUpdateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyUpdateAck)
	err := c.cc.Invoke(ctx, AFPPolicyStream_PublishPolicyUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AFPPolicyStreamServer is the server API for AFPPolicyStream service.
// All implementations must embed UnimplementedAFPPolicyStreamServer
// for forward compatibility.
//
// AFPPolicyStream is the Phase 2 runtime control plane.
// ConfigMap + fsnotify remains declarative law; this stream delivers sub-second injunctions.
type AFPPolicyStreamServer interface {
	// StreamPolicyUpdates pushes policy deltas and emergency overrides to sidecars.
	StreamPolicyUpdates(*PolicySubscribeRequest, grpc.ServerStreamingServer[PolicyUpdate]) error
	// PublishPolicyUpdate injects a one-shot override (Kill Switch, emergency clamp).
	PublishPolicyUpdate(context.Context, *PolicyUpdate) (*PolicyUpdateAck, error)
	mustEmbedUnimplementedAFPPolicyStreamServer()
}

// UnimplementedAFPPolicyStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAFPPolicyStreamServer struct{}

func (UnimplementedAFPPolicyStreamServer) StreamPolicyUpdates(*PolicySubscribeRequest, grpc.ServerStreamingServer[PolicyUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPolicyUpdates not implemented")
}
func (UnimplementedAFPPolicyStreamServer) PublishPolicyUpdate(context.Context, *PolicyUpdate) (*PolicyUpdateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPolicyUpdate not implemented")
}
func (UnimplementedAFPPolicyStreamServer) mustEmbedUnimplementedAFPPolicyStreamServer() {}
func (UnimplementedAFPPolicyStreamServer) testEmbeddedByValue()                         {}

// UnsafeAFPPolicyStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AFPPolicyStreamServer will
// result in compilation errors.
type UnsafeAFPPolicyStreamServer interface {
	mustEmbedUnimplementedAFPPolicyStreamServer()
}

func RegisterAFPPolicyStreamServer(s grpc.ServiceRegistrar, srv AFPPolicyStreamServer) {
	// If the following call panics, it indicates UnimplementedAFPPolicyStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AFPPolicyStream_ServiceDesc, srv)
}

func _AFPPolicyStream_StreamPolicyUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PolicySubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AFPPolicyStreamServer).StreamPolicyUpdates(m, &grpc.GenericServerStream[PolicySubscribeRequest, PolicyUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFPPolicyStream_StreamPolicyUpdatesServer = grpc.ServerStreamingServer[PolicyUpdate]

func _AFPPolicyStream_PublishPolicyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AFPPolicyStreamServer).PublishPolicyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AFPPolicyStream_PublishPolicyUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AFPPolicyStreamServer).PublishPolicyUpdate(ctx, req.(*PolicyUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// AFPPolicyStream_ServiceDesc is the grpc.ServiceDesc for AFPPolicyStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AFPPolicyStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afp.v1.policystream.AFPPolicyStream",
	HandlerType: (*AFPPolicyStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishPolicyUpdate",
			Handler:    _AFPPolicyStream_PublishPolicyUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPolicyUpdates",
			Handler:       _AFPPolicyStream_StreamPolicyUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "afp/v1/policy_stream.proto",
}
