// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: afp/v1/policy_stream.proto

package afppolicystream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicySource int32

const (
	PolicySource_POLICY_SOURCE_UNSPECIFIED PolicySource = 0
	PolicySource_CRD_RECONCILER            PolicySource = 1
	PolicySource_OPERATOR_CLI              PolicySource = 2
	PolicySource_EMERGENCY_KILL_SWITCH     PolicySource = 3
)

// Enum value maps for PolicySource.
var (
	PolicySource_name = map[int32]string{
		0: "POLICY_SOURCE_UNSPECIFIED",
		1: "CRD_RECONCILER",
		2: "OPERATOR_CLI",
		3: "EMERGENCY_KILL_SWITCH",
	}
	PolicySource_value = map[string]int32{
		"POLICY_SOURCE_UNSPECIFIED": 0,
		"CRD_RECONCILER":            1,
		"OPERATOR_CLI":              2,
		"EMERGENCY_KILL_SWITCH":     3,
	}
)

func (x PolicySource) Enum() *PolicySource {
	p := new(PolicySource)
	*p = x
	return p
}

func (x PolicySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicySource) Descriptor() protoreflect.EnumDescriptor {
	return file_afp_v1_policy_stream_proto_enumTypes[0].Descriptor()
}

func (PolicySource) Type() protoreflect.EnumType {
	return &file_afp_v1_policy_stream_proto_enumTypes[0]
}

func (x PolicySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicySource.Descriptor instead.
func (PolicySource) EnumDescriptor() ([]byte, []int) {
	return file_afp_v1_policy_stream_proto_rawDescGZIP(), []int{0}
}

type PolicySubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sidecar identity (typically AFP_LOCAL_DID or pod UID).
	SidecarId string `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Last acknowledged revision for idempotent resume (0 = cold start).
	LastRevision  uint64 `protobuf:"varint,3,opt,name=last_revision,json=lastRevision,proto3" json:"last_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySubscribeRequest) Reset() {
	*x = PolicySubscribeRequest{}
	mi := &file_afp_v1_policy_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySubscribeRequest) ProtoMessage() {}

func (x *PolicySubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_policy_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySubscribeRequest.ProtoReflect.Descriptor instead.
func (*PolicySubscribeRequest) Descriptor() ([]byte, []int) {
	return file_afp_v1_policy_stream_proto_rawDescGZIP(), []int{0}
}

func (x *PolicySubscribeRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *PolicySubscribeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PolicySubscribeRequest) GetLastRevision() uint64 {
	if x != nil {
		return x.LastRevision
	}
	return 0
}

type PolicyUpdate struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UpdateId     string                 `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	Revision     uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Source       PolicySource           `protobuf:"varint,3,opt,name=source,proto3,enum=afp.v1.policystream.PolicySource" json:"source,omitempty"`
	IssuedAtUnix int64                  `protobuf:"varint,4,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	// Emergency Kill Switch: all pre-flight checks return ISOLATED while active.
	KillSwitchActive bool `protobuf:"varint,5,opt,name=kill_switch_active,json=killSwitchActive,proto3" json:"kill_switch_active,omitempty"`
	// When true, drop stream overlay and fall back to ConfigMap/fsnotify law only.
	ClearOverrides bool `protobuf:"varint,6,opt,name=clear_overrides,json=clearOverrides,proto3" json:"clear_overrides,omitempty"`
	// Optional overrides. Zero values mean "leave unchanged" unless clear_overrides is set.
	EntropyLimit         float64 `protobuf:"fixed64,7,opt,name=entropy_limit,json=entropyLimit,proto3" json:"entropy_limit,omitempty"`
	MaxRecursionDepth    uint32  `protobuf:"varint,8,opt,name=max_recursion_depth,json=maxRecursionDepth,proto3" json:"max_recursion_depth,omitempty"`
	EntropyLimitSet      bool    `protobuf:"varint,9,opt,name=entropy_limit_set,json=entropyLimitSet,proto3" json:"entropy_limit_set,omitempty"`
	MaxRecursionDepthSet bool    `protobuf:"varint,10,opt,name=max_recursion_depth_set,json=maxRecursionDepthSet,proto3" json:"max_recursion_depth_set,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PolicyUpdate) Reset() {
	*x = PolicyUpdate{}
	mi := &file_afp_v1_policy_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyUpdate) ProtoMessage() {}

func (x *PolicyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_policy_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyUpdate.ProtoReflect.Descriptor instead.
func (*PolicyUpdate) Descriptor() ([]byte, []int) {
	return file_afp_v1_policy_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyUpdate) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

func (x *PolicyUpdate) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PolicyUpdate) GetSource() PolicySource {
	if x != nil {
		return x.Source
	}
	return PolicySource_POLICY_SOURCE_UNSPECIFIED
}

func (x *PolicyUpdate) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *PolicyUpdate) GetKillSwitchActive() bool {
	if x != nil {
		return x.KillSwitchActive
	}
	return false
}

func (x *PolicyUpdate) GetClearOverrides() bool {
	if x != nil {
		return x.ClearOverrides
	}
	return false
}

func (x *PolicyUpdate) GetEntropyLimit() float64 {
	if x != nil {
		return x.EntropyLimit
	}
	return 0
}

func (x *PolicyUpdate) GetMaxRecursionDepth() uint32 {
	if x != nil {
		return x.MaxRecursionDepth
	}
	return 0
}

func (x *PolicyUpdate) GetEntropyLimitSet() bool {
	if x != nil {
		return x.EntropyLimitSet
	}
	return false
}

func (x *PolicyUpdate) GetMaxRecursionDepthSet() bool {
	if x != nil {
		return x.MaxRecursionDepthSet
	}
	return false
}

type PolicyUpdateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Revision      uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyUpdateAck) Reset() {
	*x = PolicyUpdateAck{}
	mi := &file_afp_v1_policy_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyUpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyUpdateAck) ProtoMessage() {}

func (x *PolicyUpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_policy_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyUpdateAck.ProtoReflect.Descriptor instead.
func (*PolicyUpdateAck) Descriptor() ([]byte, []int) {
	return file_afp_v1_policy_stream_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyUpdateAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PolicyUpdateAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PolicyUpdateAck) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_afp_v1_policy_stream_proto protoreflect.FileDescriptor

const file_afp_v1_policy_stream_proto_rawDesc = "" +
	"\n" +
	"\x1aafp/v1/policy_stream.proto\x12\x13afp.v1.policystream\"z\n" +
	"\x16PolicySubscribeRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12#\n" +
	"\rlast_revision\x18\x03 \x01(\x04R\flastRevision\"\xb7\x03\n" +
	"\fPolicyUpdate\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x129\n" +
	"\x06source\x18\x03 \x01(\x0e2!.afp.v1.policystream.PolicySourceR\x06source\x12$\n" +
	"\x0eissued_at_unix\x18\x04 \x01(\x03R\fissuedAtUnix\x12,\n" +
	"\x12kill_switch_active\x18\x05 \x01(\bR\x10killSwitchActive\x12'\n" +
	"\x0fclear_overrides\x18\x06 \x01(\bR\x0eclearOverrides\x12#\n" +
	"\rentropy_limit\x18\a \x01(\x01R\fentropyLimit\x12.\n" +
	"\x13max_recursion_depth\x18\b \x01(\rR\x11maxRecursionDepth\x12*\n" +
	"\x11entropy_limit_set\x18\t \x01(\bR\x0fentropyLimitSet\x125\n" +
	"\x17max_recursion_depth_set\x18\n" +
	" \x01(\bR\x14maxRecursionDepthSet\"c\n" +
	"\x0fPolicyUpdateAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision*n\n" +
	"\fPolicySource\x12\x1d\n" +
	"\x19POLICY_SOURCE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCRD_RECONCILER\x10\x01\x12\x10\n" +
	"\fOPERATOR_CLI\x10\x02\x12\x19\n" +
	"\x15EMERGENCY_KILL_SWITCH\x10\x032\xda\x01\n" +
	"\x0fAFPPolicyStream\x12g\n" +
	"\x13StreamPolicyUpdates\x12+.afp.v1.policystream.PolicySubscribeRequest\x1a!.afp.v1.policystream.PolicyUpdate0\x01\x12^\n" +
	"\x13PublishPolicyUpdate\x12!.afp.v1.policystream.PolicyUpdate\x1a$.afp.v1.policystream.PolicyUpdateAckBUZSgithub.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1/policystream;afppolicystreamb\x06proto3"

var (
	file_afp_v1_policy_stream_proto_rawDescOnce sync.Once
	file_afp_v1_policy_stream_proto_rawDescData []byte
)

func file_afp_v1_policy_stream_proto_rawDescGZIP() []byte {
	file_afp_v1_policy_stream_proto_rawDescOnce.Do(func() {
		file_afp_v1_policy_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_afp_v1_policy_stream_proto_rawDesc), len(file_afp_v1_policy_stream_proto_rawDesc)))
	})
	return file_afp_v1_policy_stream_proto_rawDescData
}

var file_afp_v1_policy_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_afp_v1_policy_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_afp_v1_policy_stream_proto_goTypes = []any{
	(PolicySource)(0),              // 0: afp.v1.policystream.PolicySource
	(*PolicySubscribeRequest)(nil), // 1: afp.v1.policystream.PolicySubscribeRequest
	(*PolicyUpdate)(nil),           // 2: afp.v1.policystream.PolicyUpdate
	(*PolicyUpdateAck)(nil),        // 3: afp.v1.policystream.PolicyUpdateAck
}
var file_afp_v1_policy_stream_proto_depIdxs = []int32{
	0, // 0: afp.v1.policystream.PolicyUpdate.source:type_name -> afp.v1.policystream.PolicySource
	1, // 1: afp.v1.policystream.AFPPolicyStream.StreamPolicyUpdates:input_type -> afp.v1.policystream.PolicySubscribeRequest
	2, // 2: afp.v1.policystream.AFPPolicyStream.PublishPolicyUpdate:input_type -> afp.v1.policystream.PolicyUpdate
	2, // 3: afp.v1.policystream.AFPPolicyStream.StreamPolicyUpdates:output_type -> afp.v1.policystream.PolicyUpdate
	3, // 4: afp.v1.policystream.AFPPolicyStream.PublishPolicyUpdate:output_type -> afp.v1.policystream.PolicyUpdateAck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_afp_v1_policy_stream_proto_init() }
func file_afp_v1_policy_stream_proto_init() {
	if File_afp_v1_policy_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_afp_v1_policy_stream_proto_rawDesc), len(file_afp_v1_policy_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_afp_v1_policy_stream_proto_goTypes,
		DependencyIndexes: file_afp_v1_policy_stream_proto_depIdxs,
		EnumInfos:         file_afp_v1_policy_stream_proto_enumTypes,
		MessageInfos:      file_afp_v1_policy_stream_proto_msgTypes,
	}.Build()
	File_afp_v1_policy_stream_proto = out.File
	file_afp_v1_policy_stream_proto_goTypes = nil
	file_afp_v1_policy_stream_proto_depIdxs = nil
}
