# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sdk_ipc_pb2 as afp_dot_v1_dot_sdk__ipc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in afp/v1/sdk_ipc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AFPSidecarIPCStub(object):
    """AFPSidecarIPC is served over a Unix Domain Socket inside the same Pod as the agent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreFlightCheck = channel.unary_unary(
                '/afp.v1.sdk.AFPSidecarIPC/PreFlightCheck',
                request_serializer=afp_dot_v1_dot_sdk__ipc__pb2.PreFlightRequest.SerializeToString,
                response_deserializer=afp_dot_v1_dot_sdk__ipc__pb2.PreFlightResponse.FromString,
                _registered_method=True)
        self.ReportInternalState = channel.unary_unary(
                '/afp.v1.sdk.AFPSidecarIPC/ReportInternalState',
                request_serializer=afp_dot_v1_dot_sdk__ipc__pb2.InternalStateReport.SerializeToString,
                response_deserializer=afp_dot_v1_dot_sdk__ipc__pb2.StateAck.FromString,
                _registered_method=True)


class AFPSidecarIPCServicer(object):
    """AFPSidecarIPC is served over a Unix Domain Socket inside the same Pod as the agent.
    """

    def PreFlightCheck(self, request, context):
        """PreFlightCheck probes physical entropy before intent generation or outbound I/O.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportInternalState(self, request, context):
        """ReportInternalState feeds application-layer context into EntropyMonitor (write path).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AFPSidecarIPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreFlightCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.PreFlightCheck,
                    request_deserializer=afp_dot_v1_dot_sdk__ipc__pb2.PreFlightRequest.FromString,
                    response_serializer=afp_dot_v1_dot_sdk__ipc__pb2.PreFlightResponse.SerializeToString,
            ),
            'ReportInternalState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportInternalState,
                    request_deserializer=afp_dot_v1_dot_sdk__ipc__pb2.InternalStateReport.FromString,
                    response_serializer=afp_dot_v1_dot_sdk__ipc__pb2.StateAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'afp.v1.sdk.AFPSidecarIPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('afp.v1.sdk.AFPSidecarIPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AFPSidecarIPC(object):
    """AFPSidecarIPC is served over a Unix Domain Socket inside the same Pod as the agent.
    """

    @staticmethod
    def PreFlightCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afp.v1.sdk.AFPSidecarIPC/PreFlightCheck',
            afp_dot_v1_dot_sdk__ipc__pb2.PreFlightRequest.SerializeToString,
            afp_dot_v1_dot_sdk__ipc__pb2.PreFlightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportInternalState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/afp.v1.sdk.AFPSidecarIPC/ReportInternalState',
            afp_dot_v1_dot_sdk__ipc__pb2.InternalStateReport.SerializeToString,
            afp_dot_v1_dot_sdk__ipc__pb2.StateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
