# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: afp/v1/sdk_ipc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'afp/v1/sdk_ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x66p/v1/sdk_ipc.proto\x12\nafp.v1.sdk\"Q\n\x10PreFlightRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\ntarget_did\x18\x02 \x01(\t\x12\x17\n\x0f\x65stimated_tasks\x18\x03 \x01(\r\"\xa8\x01\n\x11PreFlightResponse\x12\x34\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32$.afp.v1.sdk.PreFlightResponse.Action\x12\x10\n\x08\x64\x65lay_ms\x18\x02 \x01(\r\x12\x14\n\x0c\x62lock_reason\x18\x03 \x01(\t\"5\n\x06\x41\x63tion\x12\x0e\n\nPERMISSIVE\x10\x00\x12\r\n\tTHROTTLED\x10\x01\x12\x0c\n\x08ISOLATED\x10\x02\"T\n\x13InternalStateReport\x12\x1f\n\x17\x63urrent_recursion_depth\x18\x01 \x01(\r\x12\x1c\n\x14\x63ontext_memory_bytes\x18\x02 \x01(\x04\"\x1c\n\x08StateAck\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xac\x01\n\rAFPSidecarIPC\x12M\n\x0ePreFlightCheck\x12\x1c.afp.v1.sdk.PreFlightRequest\x1a\x1d.afp.v1.sdk.PreFlightResponse\x12L\n\x13ReportInternalState\x12\x1f.afp.v1.sdk.InternalStateReport\x1a\x14.afp.v1.sdk.StateAckBCZAgithub.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1/sdk;afpsdkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'afp.v1.sdk_ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1/sdk;afpsdk'
  _globals['_PREFLIGHTREQUEST']._serialized_start=36
  _globals['_PREFLIGHTREQUEST']._serialized_end=117
  _globals['_PREFLIGHTRESPONSE']._serialized_start=120
  _globals['_PREFLIGHTRESPONSE']._serialized_end=288
  _globals['_PREFLIGHTRESPONSE_ACTION']._serialized_start=235
  _globals['_PREFLIGHTRESPONSE_ACTION']._serialized_end=288
  _globals['_INTERNALSTATEREPORT']._serialized_start=290
  _globals['_INTERNALSTATEREPORT']._serialized_end=374
  _globals['_STATEACK']._serialized_start=376
  _globals['_STATEACK']._serialized_end=404
  _globals['_AFPSIDECARIPC']._serialized_start=407
  _globals['_AFPSIDECARIPC']._serialized_end=579
# @@protoc_insertion_point(module_scope)
