// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: afp/v1/sdk_ipc.proto

package afpsdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreFlightResponse_Action int32

const (
	PreFlightResponse_PERMISSIVE PreFlightResponse_Action = 0
	PreFlightResponse_THROTTLED  PreFlightResponse_Action = 1
	PreFlightResponse_ISOLATED   PreFlightResponse_Action = 2
)

// Enum value maps for PreFlightResponse_Action.
var (
	PreFlightResponse_Action_name = map[int32]string{
		0: "PERMISSIVE",
		1: "THROTTLED",
		2: "ISOLATED",
	}
	PreFlightResponse_Action_value = map[string]int32{
		"PERMISSIVE": 0,
		"THROTTLED":  1,
		"ISOLATED":   2,
	}
)

func (x PreFlightResponse_Action) Enum() *PreFlightResponse_Action {
	p := new(PreFlightResponse_Action)
	*p = x
	return p
}

func (x PreFlightResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreFlightResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_afp_v1_sdk_ipc_proto_enumTypes[0].Descriptor()
}

func (PreFlightResponse_Action) Type() protoreflect.EnumType {
	return &file_afp_v1_sdk_ipc_proto_enumTypes[0]
}

func (x PreFlightResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreFlightResponse_Action.Descriptor instead.
func (PreFlightResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_afp_v1_sdk_ipc_proto_rawDescGZIP(), []int{1, 0}
}

type PreFlightRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TraceId        string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TargetDid      string                 `protobuf:"bytes,2,opt,name=target_did,json=targetDid,proto3" json:"target_did,omitempty"`
	EstimatedTasks uint32                 `protobuf:"varint,3,opt,name=estimated_tasks,json=estimatedTasks,proto3" json:"estimated_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreFlightRequest) Reset() {
	*x = PreFlightRequest{}
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreFlightRequest) ProtoMessage() {}

func (x *PreFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreFlightRequest.ProtoReflect.Descriptor instead.
func (*PreFlightRequest) Descriptor() ([]byte, []int) {
	return file_afp_v1_sdk_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *PreFlightRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PreFlightRequest) GetTargetDid() string {
	if x != nil {
		return x.TargetDid
	}
	return ""
}

func (x *PreFlightRequest) GetEstimatedTasks() uint32 {
	if x != nil {
		return x.EstimatedTasks
	}
	return 0
}

type PreFlightResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Action        PreFlightResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=afp.v1.sdk.PreFlightResponse_Action" json:"action,omitempty"`
	DelayMs       uint32                   `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	BlockReason   string                   `protobuf:"bytes,3,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreFlightResponse) Reset() {
	*x = PreFlightResponse{}
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreFlightResponse) ProtoMessage() {}

func (x *PreFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreFlightResponse.ProtoReflect.Descriptor instead.
func (*PreFlightResponse) Descriptor() ([]byte, []int) {
	return file_afp_v1_sdk_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *PreFlightResponse) GetAction() PreFlightResponse_Action {
	if x != nil {
		return x.Action
	}
	return PreFlightResponse_PERMISSIVE
}

func (x *PreFlightResponse) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *PreFlightResponse) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

type InternalStateReport struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CurrentRecursionDepth uint32                 `protobuf:"varint,1,opt,name=current_recursion_depth,json=currentRecursionDepth,proto3" json:"current_recursion_depth,omitempty"`
	ContextMemoryBytes    uint64                 `protobuf:"varint,2,opt,name=context_memory_bytes,json=contextMemoryBytes,proto3" json:"context_memory_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InternalStateReport) Reset() {
	*x = InternalStateReport{}
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalStateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalStateReport) ProtoMessage() {}

func (x *InternalStateReport) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalStateReport.ProtoReflect.Descriptor instead.
func (*InternalStateReport) Descriptor() ([]byte, []int) {
	return file_afp_v1_sdk_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *InternalStateReport) GetCurrentRecursionDepth() uint32 {
	if x != nil {
		return x.CurrentRecursionDepth
	}
	return 0
}

func (x *InternalStateReport) GetContextMemoryBytes() uint64 {
	if x != nil {
		return x.ContextMemoryBytes
	}
	return 0
}

type StateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAck) Reset() {
	*x = StateAck{}
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAck) ProtoMessage() {}

func (x *StateAck) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_sdk_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAck.ProtoReflect.Descriptor instead.
func (*StateAck) Descriptor() ([]byte, []int) {
	return file_afp_v1_sdk_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *StateAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_afp_v1_sdk_ipc_proto protoreflect.FileDescriptor

const file_afp_v1_sdk_ipc_proto_rawDesc = "" +
	"\n" +
	"\x14afp/v1/sdk_ipc.proto\x12\n" +
	"afp.v1.sdk\"u\n" +
	"\x10PreFlightRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"target_did\x18\x02 \x01(\tR\ttargetDid\x12'\n" +
	"\x0festimated_tasks\x18\x03 \x01(\rR\x0eestimatedTasks\"\xc6\x01\n" +
	"\x11PreFlightResponse\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.afp.v1.sdk.PreFlightResponse.ActionR\x06action\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\rR\adelayMs\x12!\n" +
	"\fblock_reason\x18\x03 \x01(\tR\vblockReason\"5\n" +
	"\x06Action\x12\x0e\n" +
	"\n" +
	"PERMISSIVE\x10\x00\x12\r\n" +
	"\tTHROTTLED\x10\x01\x12\f\n" +
	"\bISOLATED\x10\x02\"\x7f\n" +
	"\x13InternalStateReport\x126\n" +
	"\x17current_recursion_depth\x18\x01 \x01(\rR\x15currentRecursionDepth\x120\n" +
	"\x14context_memory_bytes\x18\x02 \x01(\x04R\x12contextMemoryBytes\"&\n" +
	"\bStateAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2\xac\x01\n" +
	"\rAFPSidecarIPC\x12M\n" +
	"\x0ePreFlightCheck\x12\x1c.afp.v1.sdk.PreFlightRequest\x1a\x1d.afp.v1.sdk.PreFlightResponse\x12L\n" +
	"\x13ReportInternalState\x12\x1f.afp.v1.sdk.InternalStateReport\x1a\x14.afp.v1.sdk.StateAckBCZAgithub.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1/sdk;afpsdkb\x06proto3"

var (
	file_afp_v1_sdk_ipc_proto_rawDescOnce sync.Once
	file_afp_v1_sdk_ipc_proto_rawDescData []byte
)

func file_afp_v1_sdk_ipc_proto_rawDescGZIP() []byte {
	file_afp_v1_sdk_ipc_proto_rawDescOnce.Do(func() {
		file_afp_v1_sdk_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_afp_v1_sdk_ipc_proto_rawDesc), len(file_afp_v1_sdk_ipc_proto_rawDesc)))
	})
	return file_afp_v1_sdk_ipc_proto_rawDescData
}

var file_afp_v1_sdk_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_afp_v1_sdk_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_afp_v1_sdk_ipc_proto_goTypes = []any{
	(PreFlightResponse_Action)(0), // 0: afp.v1.sdk.PreFlightResponse.Action
	(*PreFlightRequest)(nil),      // 1: afp.v1.sdk.PreFlightRequest
	(*PreFlightResponse)(nil),     // 2: afp.v1.sdk.PreFlightResponse
	(*InternalStateReport)(nil),   // 3: afp.v1.sdk.InternalStateReport
	(*StateAck)(nil),              // 4: afp.v1.sdk.StateAck
}
var file_afp_v1_sdk_ipc_proto_depIdxs = []int32{
	0, // 0: afp.v1.sdk.PreFlightResponse.action:type_name -> afp.v1.sdk.PreFlightResponse.Action
	1, // 1: afp.v1.sdk.AFPSidecarIPC.PreFlightCheck:input_type -> afp.v1.sdk.PreFlightRequest
	3, // 2: afp.v1.sdk.AFPSidecarIPC.ReportInternalState:input_type -> afp.v1.sdk.InternalStateReport
	2, // 3: afp.v1.sdk.AFPSidecarIPC.PreFlightCheck:output_type -> afp.v1.sdk.PreFlightResponse
	4, // 4: afp.v1.sdk.AFPSidecarIPC.ReportInternalState:output_type -> afp.v1.sdk.StateAck
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_afp_v1_sdk_ipc_proto_init() }
func file_afp_v1_sdk_ipc_proto_init() {
	if File_afp_v1_sdk_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_afp_v1_sdk_ipc_proto_rawDesc), len(file_afp_v1_sdk_ipc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_afp_v1_sdk_ipc_proto_goTypes,
		DependencyIndexes: file_afp_v1_sdk_ipc_proto_depIdxs,
		EnumInfos:         file_afp_v1_sdk_ipc_proto_enumTypes,
		MessageInfos:      file_afp_v1_sdk_ipc_proto_msgTypes,
	}.Build()
	File_afp_v1_sdk_ipc_proto = out.File
	file_afp_v1_sdk_ipc_proto_goTypes = nil
	file_afp_v1_sdk_ipc_proto_depIdxs = nil
}
