// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: afp/v1/sdk_ipc.proto

package afpsdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AFPSidecarIPC_PreFlightCheck_FullMethodName      = "/afp.v1.sdk.AFPSidecarIPC/PreFlightCheck"
	AFPSidecarIPC_ReportInternalState_FullMethodName = "/afp.v1.sdk.AFPSidecarIPC/ReportInternalState"
)

// AFPSidecarIPCClient is the client API for AFPSidecarIPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AFPSidecarIPC is served over a Unix Domain Socket inside the same Pod as the agent.
type AFPSidecarIPCClient interface {
	// PreFlightCheck probes physical entropy before intent generation or outbound I/O.
	PreFlightCheck(ctx context.Context, in *PreFlightRequest, opts ...grpc.CallOption) (*PreFlightResponse, error)
	// ReportInternalState feeds application-layer context into EntropyMonitor (write path).
	ReportInternalState(ctx context.Context, in *InternalStateReport, opts ...grpc.CallOption) (*StateAck, error)
}

type aFPSidecarIPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAFPSidecarIPCClient(cc grpc.ClientConnInterface) AFPSidecarIPCClient {
	return &aFPSidecarIPCClient{cc}
}

func (c *aFPSidecarIPCClient) PreFlightCheck(ctx context.Context, in *PreFlightRequest, opts ...grpc.CallOption) (*PreFlightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreFlightResponse)
	err := c.cc.Invoke(ctx, AFPSidecarIPC_PreFlightCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aFPSidecarIPCClient) ReportInternalState(ctx context.Context, in *InternalStateReport, opts ...grpc.CallOption) (*StateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateAck)
	err := c.cc.Invoke(ctx, AFPSidecarIPC_ReportInternalState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AFPSidecarIPCServer is the server API for AFPSidecarIPC service.
// All implementations must embed UnimplementedAFPSidecarIPCServer
// for forward compatibility.
//
// AFPSidecarIPC is served over a Unix Domain Socket inside the same Pod as the agent.
type AFPSidecarIPCServer interface {
	// PreFlightCheck probes physical entropy before intent generation or outbound I/O.
	PreFlightCheck(context.Context, *PreFlightRequest) (*PreFlightResponse, error)
	// ReportInternalState feeds application-layer context into EntropyMonitor (write path).
	ReportInternalState(context.Context, *InternalStateReport) (*StateAck, error)
	mustEmbedUnimplementedAFPSidecarIPCServer()
}

// UnimplementedAFPSidecarIPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAFPSidecarIPCServer struct{}

func (UnimplementedAFPSidecarIPCServer) PreFlightCheck(context.Context, *PreFlightRequest) (*PreFlightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreFlightCheck not implemented")
}
func (UnimplementedAFPSidecarIPCServer) ReportInternalState(context.Context, *InternalStateReport) (*StateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInternalState not implemented")
}
func (UnimplementedAFPSidecarIPCServer) mustEmbedUnimplementedAFPSidecarIPCServer() {}
func (UnimplementedAFPSidecarIPCServer) testEmbeddedByValue()                       {}

// UnsafeAFPSidecarIPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AFPSidecarIPCServer will
// result in compilation errors.
type UnsafeAFPSidecarIPCServer interface {
	mustEmbedUnimplementedAFPSidecarIPCServer()
}

func RegisterAFPSidecarIPCServer(s grpc.ServiceRegistrar, srv AFPSidecarIPCServer) {
	// If the following call panics, it indicates UnimplementedAFPSidecarIPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AFPSidecarIPC_ServiceDesc, srv)
}

func _AFPSidecarIPC_PreFlightCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AFPSidecarIPCServer).PreFlightCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AFPSidecarIPC_PreFlightCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AFPSidecarIPCServer).PreFlightCheck(ctx, req.(*PreFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AFPSidecarIPC_ReportInternalState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalStateReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AFPSidecarIPCServer).ReportInternalState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AFPSidecarIPC_ReportInternalState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AFPSidecarIPCServer).ReportInternalState(ctx, req.(*InternalStateReport))
	}
	return interceptor(ctx, in, info, handler)
}

// AFPSidecarIPC_ServiceDesc is the grpc.ServiceDesc for AFPSidecarIPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AFPSidecarIPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afp.v1.sdk.AFPSidecarIPC",
	HandlerType: (*AFPSidecarIPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreFlightCheck",
			Handler:    _AFPSidecarIPC_PreFlightCheck_Handler,
		},
		{
			MethodName: "ReportInternalState",
			Handler:    _AFPSidecarIPC_ReportInternalState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "afp/v1/sdk_ipc.proto",
}
