// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: afp/v1/governance.proto

package afpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntropyLoad struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ResourceAsymmetryRatio   float32                `protobuf:"fixed32,1,opt,name=resource_asymmetry_ratio,json=resourceAsymmetryRatio,proto3" json:"resource_asymmetry_ratio,omitempty"`
	DependencyContentionRate float32                `protobuf:"fixed32,2,opt,name=dependency_contention_rate,json=dependencyContentionRate,proto3" json:"dependency_contention_rate,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EntropyLoad) Reset() {
	*x = EntropyLoad{}
	mi := &file_afp_v1_governance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntropyLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntropyLoad) ProtoMessage() {}

func (x *EntropyLoad) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_governance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntropyLoad.ProtoReflect.Descriptor instead.
func (*EntropyLoad) Descriptor() ([]byte, []int) {
	return file_afp_v1_governance_proto_rawDescGZIP(), []int{0}
}

func (x *EntropyLoad) GetResourceAsymmetryRatio() float32 {
	if x != nil {
		return x.ResourceAsymmetryRatio
	}
	return 0
}

func (x *EntropyLoad) GetDependencyContentionRate() float32 {
	if x != nil {
		return x.DependencyContentionRate
	}
	return 0
}

type DependencyCollateral struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollateralType string                 `protobuf:"bytes,1,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty"`
	SlashThreshold float32                `protobuf:"fixed32,2,opt,name=slash_threshold,json=slashThreshold,proto3" json:"slash_threshold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DependencyCollateral) Reset() {
	*x = DependencyCollateral{}
	mi := &file_afp_v1_governance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyCollateral) ProtoMessage() {}

func (x *DependencyCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_governance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyCollateral.ProtoReflect.Descriptor instead.
func (*DependencyCollateral) Descriptor() ([]byte, []int) {
	return file_afp_v1_governance_proto_rawDescGZIP(), []int{1}
}

func (x *DependencyCollateral) GetCollateralType() string {
	if x != nil {
		return x.CollateralType
	}
	return ""
}

func (x *DependencyCollateral) GetSlashThreshold() float32 {
	if x != nil {
		return x.SlashThreshold
	}
	return 0
}

type GovernanceHeader struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PacketId              uint64                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Version               uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	HysteresisEpoch       uint64                 `protobuf:"varint,3,opt,name=hysteresis_epoch,json=hysteresisEpoch,proto3" json:"hysteresis_epoch,omitempty"`
	CoordinationTtl       uint32                 `protobuf:"varint,4,opt,name=coordination_ttl,json=coordinationTtl,proto3" json:"coordination_ttl,omitempty"`
	CvpScore              float32                `protobuf:"fixed32,5,opt,name=cvp_score,json=cvpScore,proto3" json:"cvp_score,omitempty"`
	TopologyConsensusHash []byte                 `protobuf:"bytes,6,opt,name=topology_consensus_hash,json=topologyConsensusHash,proto3" json:"topology_consensus_hash,omitempty"`
	EntropyLoad           *EntropyLoad           `protobuf:"bytes,7,opt,name=entropy_load,json=entropyLoad,proto3" json:"entropy_load,omitempty"`
	DependencyCollateral  *DependencyCollateral  `protobuf:"bytes,8,opt,name=dependency_collateral,json=dependencyCollateral,proto3" json:"dependency_collateral,omitempty"`
	TraceId               string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RecursionDepth        uint32                 `protobuf:"varint,10,opt,name=recursion_depth,json=recursionDepth,proto3" json:"recursion_depth,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GovernanceHeader) Reset() {
	*x = GovernanceHeader{}
	mi := &file_afp_v1_governance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceHeader) ProtoMessage() {}

func (x *GovernanceHeader) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_governance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceHeader.ProtoReflect.Descriptor instead.
func (*GovernanceHeader) Descriptor() ([]byte, []int) {
	return file_afp_v1_governance_proto_rawDescGZIP(), []int{2}
}

func (x *GovernanceHeader) GetPacketId() uint64 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *GovernanceHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GovernanceHeader) GetHysteresisEpoch() uint64 {
	if x != nil {
		return x.HysteresisEpoch
	}
	return 0
}

func (x *GovernanceHeader) GetCoordinationTtl() uint32 {
	if x != nil {
		return x.CoordinationTtl
	}
	return 0
}

func (x *GovernanceHeader) GetCvpScore() float32 {
	if x != nil {
		return x.CvpScore
	}
	return 0
}

func (x *GovernanceHeader) GetTopologyConsensusHash() []byte {
	if x != nil {
		return x.TopologyConsensusHash
	}
	return nil
}

func (x *GovernanceHeader) GetEntropyLoad() *EntropyLoad {
	if x != nil {
		return x.EntropyLoad
	}
	return nil
}

func (x *GovernanceHeader) GetDependencyCollateral() *DependencyCollateral {
	if x != nil {
		return x.DependencyCollateral
	}
	return nil
}

func (x *GovernanceHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GovernanceHeader) GetRecursionDepth() uint32 {
	if x != nil {
		return x.RecursionDepth
	}
	return 0
}

var File_afp_v1_governance_proto protoreflect.FileDescriptor

const file_afp_v1_governance_proto_rawDesc = "" +
	"\n" +
	"\x17afp/v1/governance.proto\x12\x06afp.v1\"\x85\x01\n" +
	"\vEntropyLoad\x128\n" +
	"\x18resource_asymmetry_ratio\x18\x01 \x01(\x02R\x16resourceAsymmetryRatio\x12<\n" +
	"\x1adependency_contention_rate\x18\x02 \x01(\x02R\x18dependencyContentionRate\"h\n" +
	"\x14DependencyCollateral\x12'\n" +
	"\x0fcollateral_type\x18\x01 \x01(\tR\x0ecollateralType\x12'\n" +
	"\x0fslash_threshold\x18\x02 \x01(\x02R\x0eslashThreshold\"\xc3\x03\n" +
	"\x10GovernanceHeader\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x04R\bpacketId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12)\n" +
	"\x10hysteresis_epoch\x18\x03 \x01(\x04R\x0fhysteresisEpoch\x12)\n" +
	"\x10coordination_ttl\x18\x04 \x01(\rR\x0fcoordinationTtl\x12\x1b\n" +
	"\tcvp_score\x18\x05 \x01(\x02R\bcvpScore\x126\n" +
	"\x17topology_consensus_hash\x18\x06 \x01(\fR\x15topologyConsensusHash\x126\n" +
	"\fentropy_load\x18\a \x01(\v2\x13.afp.v1.EntropyLoadR\ventropyLoad\x12Q\n" +
	"\x15dependency_collateral\x18\b \x01(\v2\x1c.afp.v1.DependencyCollateralR\x14dependencyCollateral\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12'\n" +
	"\x0frecursion_depth\x18\n" +
	" \x01(\rR\x0erecursionDepthB>Z<github.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1;afpv1b\x06proto3"

var (
	file_afp_v1_governance_proto_rawDescOnce sync.Once
	file_afp_v1_governance_proto_rawDescData []byte
)

func file_afp_v1_governance_proto_rawDescGZIP() []byte {
	file_afp_v1_governance_proto_rawDescOnce.Do(func() {
		file_afp_v1_governance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_afp_v1_governance_proto_rawDesc), len(file_afp_v1_governance_proto_rawDesc)))
	})
	return file_afp_v1_governance_proto_rawDescData
}

var file_afp_v1_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_afp_v1_governance_proto_goTypes = []any{
	(*EntropyLoad)(nil),          // 0: afp.v1.EntropyLoad
	(*DependencyCollateral)(nil), // 1: afp.v1.DependencyCollateral
	(*GovernanceHeader)(nil),     // 2: afp.v1.GovernanceHeader
}
var file_afp_v1_governance_proto_depIdxs = []int32{
	0, // 0: afp.v1.GovernanceHeader.entropy_load:type_name -> afp.v1.EntropyLoad
	1, // 1: afp.v1.GovernanceHeader.dependency_collateral:type_name -> afp.v1.DependencyCollateral
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_afp_v1_governance_proto_init() }
func file_afp_v1_governance_proto_init() {
	if File_afp_v1_governance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_afp_v1_governance_proto_rawDesc), len(file_afp_v1_governance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_afp_v1_governance_proto_goTypes,
		DependencyIndexes: file_afp_v1_governance_proto_depIdxs,
		MessageInfos:      file_afp_v1_governance_proto_msgTypes,
	}.Build()
	File_afp_v1_governance_proto = out.File
	file_afp_v1_governance_proto_goTypes = nil
	file_afp_v1_governance_proto_depIdxs = nil
}
