// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: afp/v1/cluster_policy.proto

package afppolicy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterPolicySpec is the declarative contract for enterprise-wide AFP governance.
// It is the schema source for the AFPClusterPolicy CRD and future gRPC policy streams.
type ClusterPolicySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespaces that receive this policy. Empty means afp-system only.
	TargetNamespaces  []string `protobuf:"bytes,1,rep,name=target_namespaces,json=targetNamespaces,proto3" json:"target_namespaces,omitempty"`
	EntropyLimit      float64  `protobuf:"fixed64,2,opt,name=entropy_limit,json=entropyLimit,proto3" json:"entropy_limit,omitempty"`
	MaxRecursionDepth uint32   `protobuf:"varint,3,opt,name=max_recursion_depth,json=maxRecursionDepth,proto3" json:"max_recursion_depth,omitempty"`
	RunMode           string   `protobuf:"bytes,4,opt,name=run_mode,json=runMode,proto3" json:"run_mode,omitempty"`
	FailMode          string   `protobuf:"bytes,5,opt,name=fail_mode,json=failMode,proto3" json:"fail_mode,omitempty"`
	MaxContextBytes   uint64   `protobuf:"varint,6,opt,name=max_context_bytes,json=maxContextBytes,proto3" json:"max_context_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterPolicySpec) Reset() {
	*x = ClusterPolicySpec{}
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterPolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterPolicySpec) ProtoMessage() {}

func (x *ClusterPolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterPolicySpec.ProtoReflect.Descriptor instead.
func (*ClusterPolicySpec) Descriptor() ([]byte, []int) {
	return file_afp_v1_cluster_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterPolicySpec) GetTargetNamespaces() []string {
	if x != nil {
		return x.TargetNamespaces
	}
	return nil
}

func (x *ClusterPolicySpec) GetEntropyLimit() float64 {
	if x != nil {
		return x.EntropyLimit
	}
	return 0
}

func (x *ClusterPolicySpec) GetMaxRecursionDepth() uint32 {
	if x != nil {
		return x.MaxRecursionDepth
	}
	return 0
}

func (x *ClusterPolicySpec) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *ClusterPolicySpec) GetFailMode() string {
	if x != nil {
		return x.FailMode
	}
	return ""
}

func (x *ClusterPolicySpec) GetMaxContextBytes() uint64 {
	if x != nil {
		return x.MaxContextBytes
	}
	return 0
}

type ClusterPolicyStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ObservedGeneration   string                 `protobuf:"bytes,1,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	Phase                string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ReconciledNamespaces []string               `protobuf:"bytes,4,rep,name=reconciled_namespaces,json=reconciledNamespaces,proto3" json:"reconciled_namespaces,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClusterPolicyStatus) Reset() {
	*x = ClusterPolicyStatus{}
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterPolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterPolicyStatus) ProtoMessage() {}

func (x *ClusterPolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterPolicyStatus.ProtoReflect.Descriptor instead.
func (*ClusterPolicyStatus) Descriptor() ([]byte, []int) {
	return file_afp_v1_cluster_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterPolicyStatus) GetObservedGeneration() string {
	if x != nil {
		return x.ObservedGeneration
	}
	return ""
}

func (x *ClusterPolicyStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ClusterPolicyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClusterPolicyStatus) GetReconciledNamespaces() []string {
	if x != nil {
		return x.ReconciledNamespaces
	}
	return nil
}

type ClusterPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ClusterPolicySpec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ClusterPolicyStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterPolicy) Reset() {
	*x = ClusterPolicy{}
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterPolicy) ProtoMessage() {}

func (x *ClusterPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_afp_v1_cluster_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterPolicy.ProtoReflect.Descriptor instead.
func (*ClusterPolicy) Descriptor() ([]byte, []int) {
	return file_afp_v1_cluster_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterPolicy) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ClusterPolicy) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ClusterPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterPolicy) GetSpec() *ClusterPolicySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ClusterPolicy) GetStatus() *ClusterPolicyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_afp_v1_cluster_policy_proto protoreflect.FileDescriptor

const file_afp_v1_cluster_policy_proto_rawDesc = "" +
	"\n" +
	"\x1bafp/v1/cluster_policy.proto\x12\rafp.v1.policy\"\xf9\x01\n" +
	"\x11ClusterPolicySpec\x12+\n" +
	"\x11target_namespaces\x18\x01 \x03(\tR\x10targetNamespaces\x12#\n" +
	"\rentropy_limit\x18\x02 \x01(\x01R\fentropyLimit\x12.\n" +
	"\x13max_recursion_depth\x18\x03 \x01(\rR\x11maxRecursionDepth\x12\x19\n" +
	"\brun_mode\x18\x04 \x01(\tR\arunMode\x12\x1b\n" +
	"\tfail_mode\x18\x05 \x01(\tR\bfailMode\x12*\n" +
	"\x11max_context_bytes\x18\x06 \x01(\x04R\x0fmaxContextBytes\"\xab\x01\n" +
	"\x13ClusterPolicyStatus\x12/\n" +
	"\x13observed_generation\x18\x01 \x01(\tR\x12observedGeneration\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x123\n" +
	"\x15reconciled_namespaces\x18\x04 \x03(\tR\x14reconciledNamespaces\"\xca\x01\n" +
	"\rClusterPolicy\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x124\n" +
	"\x04spec\x18\x04 \x01(\v2 .afp.v1.policy.ClusterPolicySpecR\x04spec\x12:\n" +
	"\x06status\x18\x05 \x01(\v2\".afp.v1.policy.ClusterPolicyStatusR\x06statusBIZGgithub.com/FilthyMudblood/aegis-fabric/pkg/protocol/v1/policy;afppolicyb\x06proto3"

var (
	file_afp_v1_cluster_policy_proto_rawDescOnce sync.Once
	file_afp_v1_cluster_policy_proto_rawDescData []byte
)

func file_afp_v1_cluster_policy_proto_rawDescGZIP() []byte {
	file_afp_v1_cluster_policy_proto_rawDescOnce.Do(func() {
		file_afp_v1_cluster_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_afp_v1_cluster_policy_proto_rawDesc), len(file_afp_v1_cluster_policy_proto_rawDesc)))
	})
	return file_afp_v1_cluster_policy_proto_rawDescData
}

var file_afp_v1_cluster_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_afp_v1_cluster_policy_proto_goTypes = []any{
	(*ClusterPolicySpec)(nil),   // 0: afp.v1.policy.ClusterPolicySpec
	(*ClusterPolicyStatus)(nil), // 1: afp.v1.policy.ClusterPolicyStatus
	(*ClusterPolicy)(nil),       // 2: afp.v1.policy.ClusterPolicy
}
var file_afp_v1_cluster_policy_proto_depIdxs = []int32{
	0, // 0: afp.v1.policy.ClusterPolicy.spec:type_name -> afp.v1.policy.ClusterPolicySpec
	1, // 1: afp.v1.policy.ClusterPolicy.status:type_name -> afp.v1.policy.ClusterPolicyStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_afp_v1_cluster_policy_proto_init() }
func file_afp_v1_cluster_policy_proto_init() {
	if File_afp_v1_cluster_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_afp_v1_cluster_policy_proto_rawDesc), len(file_afp_v1_cluster_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_afp_v1_cluster_policy_proto_goTypes,
		DependencyIndexes: file_afp_v1_cluster_policy_proto_depIdxs,
		MessageInfos:      file_afp_v1_cluster_policy_proto_msgTypes,
	}.Build()
	File_afp_v1_cluster_policy_proto = out.File
	file_afp_v1_cluster_policy_proto_goTypes = nil
	file_afp_v1_cluster_policy_proto_depIdxs = nil
}
